---

- name: copy DB init
  copy:
    src: "{{ role_path }}/files/initdb.sql"
    dest: /root/initdb.sql

- name: mariadb container
  docker_container:
    name: some-mariadb
    image: library/mariadb
    state: started
    volumes:
      - /root/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/mysql
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    restart_policy: unless-stopped
    
- name: guacd container
  docker_container:
    name: some-guacd
    image: "guacamole/guacd:{{ guacamole_version }}"
    state: started
    restart_policy: unless-stopped

- name: guacamole container
  docker_container:
    name: guacamole
    image: "guacamole/guacamole:{{ guacamole_version }}"
    state: started
    ports: "127.0.0.1:8080:8080"
    links:
      - some-guacd:guacd
      - some-mariadb:mysql
    env:
      TOTP_ENABLED: "{{ totp_enabled }}"
      TOTP_ISSUER: "{{ totp_issuer }}"
      TOTP_DIGITS: "{{totp_digits }}"
      TOTP_PERIOD: "{{ totp_period }}"
      TOTP_MODE: "{{ totp_mode }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      OPENID_AUTHORIZATION_ENDPOINT: "{{ openid_authorization_endpoint }}"
      OPENID_JWKS_ENDPOINT: "{{ openid_jwks_endpoint }}"
      OPENID_ISSUER: "{{ openid_issuer }}"
      OPENID_CLIENT_ID: "{{ openid_client_id }}"
      OPENID_REDIRECT_URI: "{{ openid_redirect_uri }}"
      OPENID_USERNAME_CLAIM_TYPE: "{{ openid_username_claim_type }}"
      OPENID_MAX_TOKEN_VALIDITY: "{{ openid_max_token_validity }}"
      EXTENSION_PRIORITY: "{{ extension_priority }}"
    restart_policy: unless-stopped
